apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grepod.fullname" . }}-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grepod.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storageSize | default "10Gi" }}
