apiVersion: v1
kind: Service
metadata:
  name: {{ include "grepod.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grepod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
  selector:
    {{- include "grepod.selectorLabels" . | nindent 4 }}
