apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grepod-data
  namespace: default
  labels:
    app.kubernetes.io/name: grepod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
